#登陆相关配置
login:
  #拿来主义
  api: "http://119.29.11.121:8080/wisedu-unified-login-api-v1.0/api/login"
  encryptApi: "https://api.ruoli.cc/wise/getEncryption"
#用户组配置
users:
  #单个用户配置，多用户在下方复制一份
  - user:
      #username 学号或者工号
      username: '********'
      #password 密码
      password: '********'
      #tellphone 电话号码
      tellphone: '********'
      #address 地址，定位信息
      address: 中国**省**市**县
      #email 接受通知消息的邮箱
      email: 1*****@qq.com
      #school 学校全称
      school: 大连大学
      #lon 当前位置经度，可以访问https://jingweidu.bmcx.com/获取
      lon: '115.212345'
      #lat 当前位置纬度
      lat: '26.582144'
#今日校园相关配置
cpdaily:
  #表单组默认选项配置
  #表单项类型，对应今日校园接口返回的fieldType字段，1代表文本，2代表单选，3代表多选，4代表图片
  defaults:
    #表单默认选项配置，按顺序，注意，只有标必填项的才处理，不会配置就执行generate.py
    - default:
        title: 你的学生类别？
        type: 2
        value: 本科生
    - default:
        title: 你属于下列哪个校区学生?
        type: 2
        value: 开发区校区
    # - default:
    #     title: 你目前是否在校？
    #     type: 2
    #     value: 不在校（实习、实训、见习等）
    - default:
        title: 你目前是否已到校？
        type: 2
        value: 已返校，本人现在学校内
    - default:
        title: 你目前是否有疑似/确诊新冠肺炎？
        type: 2
        value: 否
    - default:
        title: 你目前是否有发热、咳嗽等症状?
        type: 2
        value: 否
    - default:
        title: 你目前是否已就诊或正在住院?
        type: 2
        value: 否
    - default:
        title: 你目前是否被隔离？
        type: 2
        value: 否
    - default:
        title: 近1个月是否去过重点疫区或接触过重点疫区人士？
        type: 2
        value: 否
    - default:
        title: 近1个月是否接触过确诊病例？
        type: 2
        value: 否
    - default:
        title: 近1个月是否接触过疑似病例？
        type: 2
        value: 否
    - default:
        title: 你今天的体温是多少？
        type: 2
        value: 36~37.2℃
    - default:
        title: 本人是否承诺以上所填报的全部内容均属实、准确，不存在任何隐瞒与不实的情况，更无遗漏之处 (必填)
        type: 2
        value: 是
Info:
  ServerChan: # 填写Server酱的SCKEY
  Qsmg: # 填写Qsmg酱的SCKEY
  Email:
    enable: true
    server: 'smtp.qq.com' # 填写邮件的smtp服务器
    port: 25 # 填写邮件服务器的端口号
    account: '1******@qq.com' # 邮件服务器登录用户名
    password: '******' # 邮件服务器登录密码